steps:
# Build and push the docker
- name: 'gcr.io/cloud-builders/docker'
  args:
  - 'build'
  - '-t'
  - 'gcr.io/$PROJECT_ID/telegraf:$TAG_NAME'
  - '.'
- name: 'gcr.io/cloud-builders/docker'
  args:
  - 'push'
  - 'gcr.io/$PROJECT_ID/telegraf:$TAG_NAME'
# Deploy ot Heili cluster
- name: 'gcr.io/cloud-builders/kubectl'
  args:
  - set
  - image
  - daemonset
  - telegraf
  - telegraf=gcr.io/$PROJECT_ID/telegraf:$TAG_NAME
  env:
  - 'CLOUDSDK_COMPUTE_ZONE=us-central1'
  - 'CLOUDSDK_CONTAINER_CLUSTER=heili-us-central1'
images:
- 'gcr.io/$PROJECT_ID/telegraf:$TAG_NAME'
